### ISSUE TITLE
The new version of Edge is awesome

### ISSUE THREAD

**Issue by seanongit** [MicrosoftDocs/EdgeEnterprise#1]
Ship it soon!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d5289fa-f5a3-fb9f-ec23-f7de2d1f97d7
* Version Independent ID: ac5d33dc-7386-5674-ba3b-1db87ec72b09
* Content: [Overview of Edge in the enterprise](https://docs.microsoft.com/en-us/DeployEdge/overview-edge-in-the-enterprise#feedback)
* Content Source: [edgeenterprise/overview-edge-in-the-enterprise.md](https://github.com/MicrosoftDocs/EdgeEnterprise-pr/blob/live/edgeenterprise/overview-edge-in-the-enterprise.md)
* Product: **microsoft-edge**
* GitHub Login: @jwhit-MSFT
* Microsoft Alias: **kwjot**

**Comment by distrax1988** [comment]
Rock on!
