### ISSUE TITLE
Known issues should be Resolved issues for Version 81.0.416.53: April 13

### ISSUE THREAD

**Issue by Alpha-89** [MicrosoftDocs/EdgeEnterprise#106]
I think the Known Issues are actually Resolved Issues under version: Version 81.0.416.53: April 13. We had issues with one of the bugs which now seems resolved. Title is a bit unclear.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fb3b598-06c4-80d8-6095-e790a184a12b
* Version Independent ID: ad7a2d15-1935-a76d-1823-e8dc347024b3
* Content: [Microsoft Edge release notes for Stable Channel](https://docs.microsoft.com/en-us/DeployEdge/microsoft-edge-relnote-stable-channel)
* Content Source: [edgeenterprise/microsoft-edge-relnote-stable-channel.md](https://github.com/MicrosoftDocs/EdgeEnterprise/blob/public/edgeenterprise/microsoft-edge-relnote-stable-channel.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **kvice**

**Comment by dan-wesley** [comment]
@Alpha-89 Thank you for pointing that out. A correction was pushed to live about 8 minutes ago
