### ISSUE TITLE
Microsoft Edge Enterprise Security Defaults

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/EdgeEnterprise#107]
Hello,
Do you know if there some recommended policy exists for Edge security configuration?
Like from baseline policy?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d47a3485-ce79-9bbf-aac2-060792af6d06
* Version Independent ID: 9e9eacea-96fd-6856-da7e-7149edefabe4
* Content: [Configure Microsoft Edge policy settings for Windows using Microsoft Intune](https://docs.microsoft.com/en-us/DeployEdge/configure-edge-with-intune)
* Content Source: [edgeenterprise/configure-edge-with-intune.md](https://github.com/MicrosoftDocs/EdgeEnterprise/blob/public/edgeenterprise/configure-edge-with-intune.md)
* Product: **microsoft-edge**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by Brianalt-Msft** [comment]
Hi @lightupdifire, Check out the [Microsoft Security Baselines blog](https://techcommunity.microsoft.com/t5/microsoft-security-baselines/bg-p/Microsoft-Security-Baselines) for the latest Microsoft Edge Security Baseline details.

**Comment by lightupdifire** [comment]
@Brianalt-Msft , Thanks, I got this in mind later after opened this case :)
