### ISSUE TITLE
MSI Installer x64

### ISSUE THREAD

**Issue by rohithello** [MicrosoftDocs/EdgeEnterprise#108]
Installed MSI v81.0.416.53 (MicrosoftEdgeEnterpriseX64.msi) on a Win10 Pro 1803 machine and it fails but installs fine on 1909 build. Any suggestion what could have gone wrong?

**Comment by RAJU2529** [comment]
@rohithello . Installation is possible for 64bit enterprise msi edition, i have installed  81.0.416.68  64bit msi on windows 10 1909_18363.815

**Comment by SmithPlatts** [comment]
> Installed MSI v81.0.416.53 (MicrosoftEdgeEnterpriseX64.msi) on a Win10 Pro 1803 machine and it fails but installs fine on 1909 build. Any suggestion what could have gone wrong? 

Can you run the install commend (msiexec.exe) with logging enabled? That should give a pretty good idea as to what's causing it to fail.

**Comment by rohithello** [comment]
> > Installed MSI v81.0.416.53 (MicrosoftEdgeEnterpriseX64.msi) on a Win10 Pro 1803 machine and it fails but installs fine on 1909 build. Any suggestion what could have gone wrong?
> 
> Can you run the install commend (msiexec.exe) with logging enabled? That should give a pretty good idea as to what's causing it to fail.

**Comment by rohithello** [comment]
[Microsoft_Microsoft.Edge_81.0.416.53_R00_I.log](https://github.com/MicrosoftDocs/EdgeEnterprise/files/4611855/Microsoft_Microsoft.Edge_81.0.416.53_R00_I.log)
See the logs attached. I believe it has to do with Un-installing one of the existing components.

**Comment by rohithello** [comment]
> @rohithello . Installation is possible for 64bit enterprise msi edition, i have installed 81.0.416.68 64bit msi on windows 10 1909_18363.815

Thanks for the reply but that is not what I asked. Were you able to install on Win10 1803 build?

**Comment by RAJU2529** [comment]
@rohithello . I have only 1909 version

**Comment by SmithPlatts** [comment]
> [Microsoft_Microsoft.Edge_81.0.416.53_R00_I.log](https://github.com/MicrosoftDocs/EdgeEnterprise/files/4611855/Microsoft_Microsoft.Edge_81.0.416.53_R00_I.log)
> See the logs attached. I believe it has to do with Un-installing one of the existing components.

Lines 404, 407, and 410 have the info you need to get started:

`404: MSI (s) (68:AC) [15:18:36:075]: Note: 1: 1722 2: DoInstall 3: C:\WINDOWS\Installer\MSI4C46.tmp 4: /silent /install "appguid={56EB18F8-B008-4CBD-B6D2-8C97FE7E9062}&appname=Microsoft Edge&needsAdmin=True&usagestats=0&ap=stable-arch_x64" /installsource enterprisemsi /appargs "appguid={56EB18F8-B008-4CBD-B6D2-8C97FE7E9062}&installerdata=%7B%22distribution%22%3A%7B%22msi%22%3Atrue%2C%22system_level%22%3Atrue%2C%22verbose_logging%22%3Atrue%2C%22msi_product_id%22%3A%224793C66E-8648-3703-ABBB-AA78ED9E93C4%22%2C%22allow_downgrade%22%3Afalse%2C%22do_not_create_desktop_shortcut%22%3Afalse%7D%7D"`

`407: CustomAction DoInstall returned actual error code -2147219674 (note this may not be 100% accurate if translation happened inside sandbox)`

`410: MSI (s) (68:AC) [15:18:36:075]: Product: Microsoft Edge -- Error 1722. There is a problem with this Windows Installer package. A program run as part of the setup did not finish as expected. Contact your support personnel or package vendor.  Action DoInstall, location: C:\WINDOWS\Installer\MSI4C46.tmp, command: /silent /install "appguid={56EB18F8-B008-4CBD-B6D2-8C97FE7E9062}&appname=Microsoft Edge&needsAdmin=True&usagestats=0&ap=stable-arch_x64" /installsource enterprisemsi /appargs "appguid={56EB18F8-B008-4CBD-B6D2-8C97FE7E9062}&installerdata=%7B%22distribution%22%3A%7B%22msi%22%3Atrue%2C%22system_level%22%3Atrue%2C%22verbose_logging%22%3Atrue%2C%22msi_product_id%22%3A%224793C66E-8648-3703-ABBB-AA78ED9E93C4%22%2C%22allow_downgrade%22%3Afalse%2C%22do_not_create_desktop_shortcut%22%3Afalse%7D%7D" `

Can you confirm that on this 1803 system you have the right Windows Updates: https://docs.microsoft.com/en-us/DeployEdge/microsoft-edge-sysupdate-windows-updates

This seems to be the primary cause of that specific error. From what I can tell, the update allows new Edge to 'disable' Legacy Edge, and without it the custom command fails.

**Comment by rohithello** [comment]
@SmithPlatts Thankyou. You are right, I installed the update as recommended and the installation went fine. No issues. Closing the case!!
