### ISSUE TITLE
localStorage data is not migrated when Edge legacy is updated to New Edge

### ISSUE THREAD

**Issue by noishiza** [MicrosoftDocs/EdgeEnterprise#115]
localStorage data is not migrated when Edge legacy is updated to New Edge.
I would appreciated it if you could consider to reflect in the document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d14f4f17-3016-b854-2707-798f6d89d271
* Version Independent ID: 50998e79-0c55-9f57-8d8b-85273897c064
* Content: [Frequently asked questions about Edge in the enterprise](https://docs.microsoft.com/en-us/deployedge/faqs-edge-in-the-enterprise)
* Content Source: [edgeenterprise/faqs-edge-in-the-enterprise.md](https://github.com/MicrosoftDocs/EdgeEnterprise/blob/public/edgeenterprise/faqs-edge-in-the-enterprise.md)
* Product: **microsoft-edge**
* GitHub Login: @jwhit-MSFT
* Microsoft Alias: **jwhit**

**Comment by dan-wesley** [comment]
@noishiza Thank you for pointing this out. I'll pass this on.
