### ISSUE TITLE
Security Update Guide, bad link.

### ISSUE THREAD

**Issue by 2ndcahl** [MicrosoftDocs/EdgeEnterprise#119]
Sorry to open a ticket for this page, as it is actually the Security Update Guide that you link to, that has the problem. I just don't know who to contact, so I'm trying here.
Anyway, on the Security Update Guide, there are multiple links to Chrome Releases Blog, but the link is invalid. I believe that the correct link should be this:
https://chromereleases.googleblog.com/search/label/Stable%20updates

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76912f35-f62c-bd99-60fb-b11d3d40ba04
* Version Independent ID: 01fba630-3a9a-6a9e-2d24-a6a47b8e6926
* Content: [Release notes for Microsoft Edge Security Updates](https://docs.microsoft.com/en-us/DeployEdge/microsoft-edge-relnotes-security#feedback)
* Content Source: [edgeenterprise/microsoft-edge-relnotes-security.md](https://github.com/MicrosoftDocs/EdgeEnterprise/blob/public/edgeenterprise/microsoft-edge-relnotes-security.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **aguta**

**Comment by dan-wesley** [comment]
@2ndcahl Thank you for calling this out, we'll follow up and get this fixed.

**Comment by RAJU2529** [comment]
@2ndcahl . @dan-wesley . just now I checked security update guide, all links are working.

Moreover @2ndcahl.  below link only support for google chrome browser
**https://chromereleases.googleblog.com/search/label/Stable%20updates**

![Capture1](https://user-images.githubusercontent.com/3296790/81702181-9422e780-9488-11ea-925c-c3cbc012ca0b.JPG)

**Comment by 2ndcahl** [comment]
> @2ndcahl . @dan-wesley . just now I checked security update guide, all links are working.

Thank you both of you. I can confirm the same here. I consider this issue closed.
