### ISSUE TITLE
Additional available policies improperly formatted

### ISSUE THREAD

**Issue by Vivek-Raman** [MicrosoftDocs/EdgeEnterprise#12]
The table breaks in the middle, after ClickOnceEnabled

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1cd3ad5-bb4a-54ff-84e7-18ca0b11368f
* Version Independent ID: 984abd8f-45eb-737b-ad74-07ec8261f9eb
* Content: [Microsoft Edge Browser Policy Documentation](https://docs.microsoft.com/en-us/DeployEdge/microsoft-edge-policies#feedback)
* Content Source: [edgeenterprise/microsoft-edge-policies.md](https://github.com/MicrosoftDocs/EdgeEnterprise-pr/blob/live/edgeenterprise/microsoft-edge-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @Brianalt-Msft
* Microsoft Alias: **stmoody**

**Comment by Brianalt-Msft** [comment]
Fixed. Thank you for reporting it.
