### ISSUE TITLE
Policies not loading from preferences (MacOS)

### ISSUE THREAD

**Issue by RobotLimeLtd** [MicrosoftDocs/EdgeEnterprise#120]
In the MacOS version, I've tried to add polices exactly as per google Chrome, e.g.

    defaults write com.microsoft.edgemac AlwaysOpenPdfExternally -bool true

However, on reloading the policies or quitting and relaunching Edge, the policy change does not appear under edge://policy, even though I can see the new settings with "defaults read com.microsoft.edgemac" and also by opening the preferences (.plist) file manually.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1cd3ad5-bb4a-54ff-84e7-18ca0b11368f
* Version Independent ID: 984abd8f-45eb-737b-ad74-07ec8261f9eb
* Content: [Microsoft Edge Browser Policy Documentation](https://docs.microsoft.com/en-gb/DeployEdge/microsoft-edge-policies#feedback)
* Content Source: [edgeenterprise/microsoft-edge-policies.md](https://github.com/MicrosoftDocs/EdgeEnterprise/blob/public/edgeenterprise/microsoft-edge-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @Brianalt-Msft
* Microsoft Alias: **stmoody**

**Comment by Brianalt-Msft** [comment]
The preference domain for Microsoft Edge is "com.microsoft.Edge". You can learn more at https://docs.microsoft.com/DeployEdge/configure-microsoft-edge-on-mac

**Comment by RobotLimeLtd** [comment]
Then that is rather confusing, because Edge for macOS ships and installs a .plist file with domain com.microsoft.edgemac which already contains the same default keys as the equivalent Chrome plist file.
