### ISSUE TITLE
Subscribe?

### ISSUE THREAD

**Issue by ericlaw1979** [MicrosoftDocs/EdgeEnterprise#124]
It would be neat if there were a way to subscribe to changes in this page via email.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fb3b598-06c4-80d8-6095-e790a184a12b
* Version Independent ID: ad7a2d15-1935-a76d-1823-e8dc347024b3
* Content: [Microsoft Edge release notes for Stable Channel](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-relnote-stable-channel#feedback)
* Content Source: [edgeenterprise/microsoft-edge-relnote-stable-channel.md](https://github.com/MicrosoftDocs/EdgeEnterprise/blob/public/edgeenterprise/microsoft-edge-relnote-stable-channel.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **kvice**

**Comment by dan-wesley** [comment]
@ericlaw1979  I agree, like a subscription that goes out automatically to subscribers. Unfortunately our updated content page that gets refreshed weekly only indicates that a  page is touched, not what the changes are.

**Comment by dan-wesley** [comment]
@ericlaw1979 At Sean's suggestion I've started adding notes to articles that were touched the preceding week. It's manual but does help a bit.  For example: https://docs.microsoft.com/en-us/DeployEdge/microsoft-edge-content-updates
