### ISSUE TITLE
Be mindful of the proper use of acronyms

### ISSUE THREAD

**Issue by v-lorm** [MicrosoftDocs/EdgeEnterprise#132]
Please refer to the Cloud Style guide when you use acronyms AD is not an approved acronym for Active Directory. Neither is AAD approved for Azure AD.

**Azure Active Directory**
The identity service in Microsoft Azure that provides identity management and access control capabilities through a REST-based API.

Guidelines

First mention: Microsoft Azure Active Directory (Azure AD)

You can omit Microsoft if at least one of the following conditions applies:

The Microsoft logo appears in proximity to the Azure service name—like on the same screen or surface.
The word Microsoft has already been used in text earlier in the communication—like in an earlier reference to a product name.
Subsequent mentions: Azure AD

It's not acceptable to use the full acronym AAD or just AD.

Always use Azure to distinguish the service name as an Azure service.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50e0a670-8656-c0d4-9a1c-217ce12a7fea
* Version Independent ID: 25300d2f-003c-1c3d-4038-2cbab20699ca
* Content: [Microsoft Edge identity support and configuration](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-security-identity)
* Content Source: [edgeenterprise/microsoft-edge-security-identity.md](https://github.com/MicrosoftDocs/EdgeEnterprise/blob/public/edgeenterprise/microsoft-edge-security-identity.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **kvice**

**Comment by dan-wesley** [comment]
@v-lorm  Thank you for catching this, We'll get this article updated.
