### ISSUE TITLE
Java Runtime Support

### ISSUE THREAD

**Issue by GeoSimos** [MicrosoftDocs/EdgeEnterprise#14]
I would like to ask if Java Runtime Engine is supported in IE Mode as it is in Internet Explorer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aae869a8-2ae4-d28f-6c85-c1190609f87b
* Version Independent ID: e2bcb1d6-27f7-5e30-ae6b-7acb5ee94098
* Content: [Use Microsoft Edge with IE mode](https://docs.microsoft.com/en-us/DeployEdge/edge-ie-mode)
* Content Source: [edgeenterprise/edge-ie-mode.md](https://github.com/MicrosoftDocs/EdgeEnterprise-pr/blob/live/edgeenterprise/edge-ie-mode.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **kvice**

**Comment by dan-wesley** [comment]
The Java Runtime Engine is supported in IE Mode. Java isn't installed by default, so you need to install it from java.com (per the support.microsoft.com instructions). It works in both environments:  https://support.microsoft.com/en-us/help/17431/windows-internet-explorer-install-java
