### ISSUE TITLE
Spell of data types is wrong in SyncTypesListDisabled part on ja-jp page

### ISSUE THREAD

**Issue by kashimaki** [MicrosoftDocs/EdgeEnterprise#141]
Spell of data types is wrong in SyncTypesListDisabled section on ja-jp page.
Error string : addressAndMore
Expected string  : addressesAndMore

![japanese_page](https://user-images.githubusercontent.com/51355648/85532263-8301f480-b64a-11ea-9dd3-6e4bbac59129.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1cd3ad5-bb4a-54ff-84e7-18ca0b11368f
* Version Independent ID: 984abd8f-45eb-737b-ad74-07ec8261f9eb
* Content: [Microsoft Edge Browser Policy Documentation](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#synctypeslistdisabled)
* Content Source: [edgeenterprise/microsoft-edge-policies.md](https://github.com/MicrosoftDocs/EdgeEnterprise/blob/public/edgeenterprise/microsoft-edge-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @Brianalt-Msft
* Microsoft Alias: **stmoody**

**Comment by TinaMcN** [comment]
@kashimaki thank you for reporting the issue.  @OfficeGlobal please fix the issue (bug 27205)

**Comment by OfficeGlobal** [comment]
@kashimaki the typo was corrected and re-published at live page
