### ISSUE TITLE
Folder location for master_preference file

### ISSUE THREAD

**Issue by MarkusBux** [MicrosoftDocs/EdgeEnterprise#142]
I'm currently trying to get the master_preference file to work with the new Edge.
During my testing and troubleshooting, I recognised that the folder mentioned within the documentation is not correct.

The path "/Library/Microsoft/Microsoft Edge Master Preferences” needs to be “/Library/Application Support/Microsoft/Microsoft Edge Master Preferences"

At least if you monitor the filesystem with `fs_usage | grep -i master` it will display the mentioned path unter "Application Support".

<img width="1271" alt="image" src="https://user-images.githubusercontent.com/46794913/85727808-9d45dc00-b6f7-11ea-8d77-99a292eff81b.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c05c4e5-63bf-1b01-52e5-bd7ee10c737e
* Version Independent ID: 4ab1fe14-adf0-4588-19fd-5cac5e703b13
* Content: [Configure Microsoft Edge for macOS using a .plist](https://docs.microsoft.com/en-us/deployedge/configure-microsoft-edge-on-mac)
* Content Source: [edgeenterprise/configure-microsoft-edge-on-mac.md](https://github.com/MicrosoftDocs/EdgeEnterprise/blob/public/edgeenterprise/configure-microsoft-edge-on-mac.md)
* Product: **microsoft-edge**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **brianalt**

**Comment by RAJU2529** [comment]
@e0i. Assign user to review this PR.
