### ISSUE TITLE
Restoring Edge Legacy doesn't work on 2004

### ISSUE THREAD

**Issue by Louis-DR** [MicrosoftDocs/EdgeEnterprise#144]
Restoring Edge Legacy doesn't seem to work using this regedit fix after the 2004 update (using the regedit after Edge Chromium was installed automatically through the 2004 update). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d96bfa14-a7be-f140-f914-564fe81c94e8
* Version Independent ID: 8343f63e-b2e4-27bc-11ad-3db51c4e3f03
* Content: [Access the old version of Microsoft Edge](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-sysupdate-access-old-edge)
* Content Source: [edgeenterprise/microsoft-edge-sysupdate-access-old-edge.md](https://github.com/MicrosoftDocs/EdgeEnterprise/blob/public/edgeenterprise/microsoft-edge-sysupdate-access-old-edge.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **jtkim**

**Comment by cew6992** [comment]
Thanks for reporting. It would be best if you can file a support ticket. More info on how to do that is here: https://microsoftedgesupport.microsoft.com/hc/en-us.

**Comment by RAJU2529** [comment]
@cew6992 , Thanks for the support site link, it will be useful to many users. Thanks a lot.

**Comment by RAJU2529** [comment]
@Louis-DR , if possible remove a chromium-based browser from the control panel.

**Comment by jshwong** [comment]
For me, it worked all the way to Windows version 20H2, until cumulative update KB4568831 broke it.  Removing this update failed to restore it even though the registry fix was still in place.

**Comment by bahnjee** [comment]
Any update on this?  I've just found a problem that's going to require quite a few users to have access to Edge Legacy but even with both Registry settings (Allowsxs & BrowserReplacement) verified in place (as set by GPO), my test machine running 2004 still routes "Microsoft Edge Legacy" from Start menu to new Edge.  Have run `gpupdate` as well as rebooted...still no joy.

**Comment by dan-wesley** [comment]
@bahnjee Please file a support ticket. More info on how to do that is here: https://microsoftedgesupport.microsoft.com/hc/en-us.
