### ISSUE TITLE
update the details

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/EdgeEnterprise#149]
just i installed edge chromium-based browser version 83.0.478.64: on 14th july 2020.
I tried to edit this article, then i found some issues. So update latest version details from your side.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fb3b598-06c4-80d8-6095-e790a184a12b
* Version Independent ID: ad7a2d15-1935-a76d-1823-e8dc347024b3
* Content: [Microsoft Edge release notes for Stable Channel](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-relnote-stable-channel)
* Content Source: [edgeenterprise/microsoft-edge-relnote-stable-channel.md](https://github.com/MicrosoftDocs/EdgeEnterprise/blob/public/edgeenterprise/microsoft-edge-relnote-stable-channel.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **aguta**

**Comment by RAJU2529** [comment]
@e0i. some sentences are invisible in the EDIT page, but visible in the main page.

Version 83.0.478.61: July 7
Fixed various bugs and performance issues.

Version 83.0.478.58: June 30
Fixed various bugs and performance issues.

So please look into this issue.

**Comment by dan-wesley** [comment]
@RAJU2529 @aguta 
Thank you for your feedback. I'm currently working on the release notes for yesterday's minor release. Why were you trying to EDIT the release notes?

**Comment by RAJU2529** [comment]
@dan-wesley . i tried to add the latest version number

**Comment by RAJU2529** [comment]
@dan-wesley . Blue colour sentences are missing in edit page.

**Comment by dan-wesley** [comment]
@RAJU2529 
As much as I appreciate you trying to do my job, you need to know markdown works and how the final pages are published for public viewing.
The main page in EDIT provides the headers that are used to generate the blue text. This is consumed by another file.
The left nav bar is created by yet another file, which also consumes the main file.
As an fyi, the draft for the release note update is currently being reviewed and will be published this morning.
thanks
dan

**Comment by RAJU2529** [comment]
@dan-wesley . Thanks for reply. So can I close this issue without your permission ?

**Comment by dan-wesley** [comment]
@RAJU2529 yes please

**Comment by dan-wesley** [comment]
@RAJU2529 release updated and live at https://docs.microsoft.com/en-us/DeployEdge/microsoft-edge-relnote-stable-channel

**Comment by RAJU2529** [comment]
@dan-wesley . Thanks for wonderful speed job. Great Sir. 
I am closing this issue.

**Comment by e0i** [comment]
@RAJU2529 We do not handle the issues of this repository.
