### ISSUE TITLE
GA Release

### ISSUE THREAD

**Issue by jerjar01** [MicrosoftDocs/EdgeEnterprise#15]
When is the GA release planned for Chromium Edge?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbf6f010-8ab9-6ff3-e2c2-74e4973a9985
* Version Independent ID: ab1758ae-311d-d4dc-c55c-888708c97a0f
* Content: [Microsoft Edge channel overview](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-channels#feedback)
* Content Source: [edgeenterprise/microsoft-edge-channels.md](https://github.com/MicrosoftDocs/EdgeEnterprise-pr/blob/live/edgeenterprise/microsoft-edge-channels.md)
* Product: **microsoft-edge**
* GitHub Login: @jwhit-MSFT
* Microsoft Alias: **kwjot**

**Comment by stevennyman** [comment]
Starting January 15, 2020.

**Comment by arramranjith** [comment]
Do you have a official website that says about the GA release date?

**Comment by stevennyman** [comment]
https://blogs.windows.com/msedgedev/2019/11/04/edge-chromium-release-candidate-get-ready/
