### ISSUE TITLE
Microsoft Edge policy settings are not working

### ISSUE THREAD

**Issue by aimnfires** [MicrosoftDocs/EdgeEnterprise#162]
I copied the associated files (admx & adml) in the appropriate folders on my standalone computer (joined to a domain). When I go into group policy editor I see Microsoft Edge folders/settings under the administrative templates folder in the computer configuration and user configuration. I have set a few policies (ie default pop-up window setting to enable/allow sites to show pop-ups). Nothing is happening. I go to edge://policy and there is nothing listed. I have setup chrome policy's (about the same way) with no problems. What am I doing wrong ??  Thanks !!

**Comment by OftKilted** [comment]
According to the section on [Testing your policies](https://docs.microsoft.com/en-us/deployedge/configure-microsoft-edge#3-test-your-policies)  “You may need to close and reopen Microsoft Edge if it was open while you were configuring policy settings.“ 

Was that part of your process?

**Comment by aimnfires** [comment]
yes I have closed, reopen edge and even rebooted after make a policy change. I have uninstalled/reinstalled edge. Downloaded the policy file a second time. nothing is working. I guess my next step is to do a fresh windows install and try it unless someone tells me I might not be doing. thanks for your help !!

**Comment by OftKilted** [comment]
There are several versions of policies for Edge. One of which is for the legacy version, which is installed by default and doesn’t affect the new version of edge at all.  What is the policy path?

**Comment by SmithPlatts** [comment]
Depending on how your GP Central Store is configured, you may need to override the setting on your client device to permit local ADMX loading: https://support.microsoft.com/en-us/help/3087759/how-to-create-and-manage-the-central-store-for-group-policy-administra
See section **Updating the Administrative Templates files**

I have had to do this a few times, annoyingly. We have a SCCM package that flips this setting between 0 and 1, so it's easy to test and reverse.

**Comment by aimnfires** [comment]
the install & policy file I downloaded was version 84 build 84.0.522.52 platform windows 64-bit.  I put the admx files in c:\windows\policyDefinitions\   and the adml files in c:\windows\policyDefinitions\en-US.  I do see the template in group policy editor its just when I update a policy (ie default pop-up window setting to enable/allow sites to show pop-ups). Nothing is happening. To SmithPlatts : I read info on the link you sent me. I think this is for setting up policies on a domain controller ?? I am trying to set up a (local) group policy on a stand alone computer. Thank you (OftKilted & SmithPlatts) for your replies !!

**Comment by aimnfires** [comment]
OK. I just did the same procedures on a fresh windows install and it worked. Not sure what the problem was with the computer I was working with. Thank you (OftKilted & SmithPlatts) for your help  !!
