### ISSUE TITLE
add 84.0.522.58

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/EdgeEnterprise#165]
Please add  stable v 84.0.522.58 is  released on 10th august 2020
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22caa093-65a7-c99b-1c4b-d394ac3ddc15
* Version Independent ID: d7b475b8-78dd-3068-12f1-24c96eb3c6e9
* Content: [Microsoft Edge release schedule](https://docs.microsoft.com/en-us/DeployEdge/microsoft-edge-release-schedule)
* Content Source: [edgeenterprise/microsoft-edge-release-schedule.md](https://github.com/MicrosoftDocs/EdgeEnterprise/blob/public/edgeenterprise/microsoft-edge-release-schedule.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **aguta**

**Comment by RAJU2529** [comment]
I could not able to find fixed issues information in release 84.0.522.58, so i didn't create PR

**Comment by dan-wesley** [comment]
@RAJU2529 
We typically update the release notes the same day the build is released. Which was yesterday and which was done. Sorry, we can't update release notes before a version is released.
We do not list fixed issues in minor release updates.
@appcompatguy  do  you have anything to add?

**Comment by RAJU2529** [comment]
@dan-wesley . Thanks sir for your kind reply, V84.0.522.58 can be downloaded from below site,

**https://www.microsoft.com/en-us/edge/business/download**
Today i downloaded and installed successfully.
