### ISSUE TITLE
Open in IE Mode Manually

### ISSUE THREAD

**Issue by fowl2** [MicrosoftDocs/EdgeEnterprise#18]
Is it possible to open a site/tab in IE mode through the user interface (or a command line, etc.) for testing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aae869a8-2ae4-d28f-6c85-c1190609f87b
* Version Independent ID: e2bcb1d6-27f7-5e30-ae6b-7acb5ee94098
* Content: [Use Microsoft Edge with IE mode](https://docs.microsoft.com/en-us/deployedge/edge-ie-mode#configure-all-intranet-sites)
* Content Source: [edgeenterprise/edge-ie-mode.md](https://github.com/MicrosoftDocs/EdgeEnterprise-pr/blob/live/edgeenterprise/edge-ie-mode.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **kvice**

**Comment by UnidentifiedTag** [comment]
Would be nice wouldn't it, hopefully someone from Microsoft see's this request and add's it as a feature

**Comment by thedroidkid** [comment]
Hey so I found a way only for testing purposes of course. 
run the following command
msedge --ie-mode-test
