### ISSUE TITLE
Can you apply the same settings with User Configuration?

### ISSUE THREAD

**Issue by averagelistedmodem** [MicrosoftDocs/EdgeEnterprise#2]
Can you apply the same settings with User Configuration? Or do you have to use Computer Configuration?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aae869a8-2ae4-d28f-6c85-c1190609f87b
* Version Independent ID: e2bcb1d6-27f7-5e30-ae6b-7acb5ee94098
* Content: [Use Microsoft Edge with IE mode](https://docs.microsoft.com/en-us/DeployEdge/edge-ie-mode#feedback)
* Content Source: [edgeenterprise/edge-ie-mode.md](https://github.com/MicrosoftDocs/EdgeEnterprise-pr/blob/live/edgeenterprise/edge-ie-mode.md)
* Product: **microsoft-edge**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by FreekBloemhof** [comment]
I tried this with NewTabPageLocation in HKCU:\Software\Policies\Microsoft\Edge and it works as expected!

**Comment by kelleyvice-msft** [comment]
@averagelistedmodem, thanks for reaching out. Yes, the same GPO settings are available in both **User** and **Computer** scopes. I'll bring this back to the writing team to reflect this in the topic.
Kelley

**Comment by UnidentifiedTag** [comment]
@FreekBloemhof where is "HKCU:\" in the registry? do you mean "HKEY_CURRENT_USER" or "HKEY_LOCAL_MACHINE" ? 
Please be Clear on locations 
Thank you

**Comment by OftKilted** [comment]
> @FreekBloemhof where is "HKCU:" in the registry? do you mean "HKEY_CURRENT_USER" or "HKEY_LOCAL_MACHINE" ?
> Please be Clear on locations
> Thank you

@unidentifiedtag - Typically "HKCU" == HKEY_CURRENT_USER "HKLM" == HKEY_LOCAL_MACHINE
