### ISSUE TITLE
Mismatch between text and examples

### ISSUE THREAD

**Issue by DDunphy** [MicrosoftDocs/EdgeEnterprise#20]
The text states "MSEdgeDHTML", however, the examples have a "B" rather than a "D".  Which is the proper instruction?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d80a2f5-5b21-a16b-c401-5e1c40be6f00
* Version Independent ID: b63c5b42-443b-687c-a445-58fa4de6b84b
* Content: [Set Microsoft Edge as the default browser on Windows](https://docs.microsoft.com/en-us/deployedge/edge-default-browser#feedback)
* Content Source: [edgeenterprise/edge-default-browser.md](https://github.com/MicrosoftDocs/EdgeEnterprise-pr/blob/live/edgeenterprise/edge-default-browser.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **brianalt**

**Comment by dan-wesley** [comment]
The text in the XML example is for Microsoft Edge **B**eta, so the id is "MSEdge**B**HTML"
The text in the note is for Microsoft Edge **D**ev, so the id is MSEdge**D**HTML
