### ISSUE TITLE
Schema v.2.1?

### ISSUE THREAD

**Issue by matziq** [MicrosoftDocs/EdgeEnterprise#21]
This blurb mentions v.2.1 but I can't find any information on v.2.1.
"Enterprise Mode schema v.1 isn't supported for IE mode integration. If you are currently using schema v.1 with Internet Explorer 11, you must upgrade to schema v.2 or v.2.1. For more information, see Enterprise Mode schema v.2 guidance."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aae869a8-2ae4-d28f-6c85-c1190609f87b
* Version Independent ID: e2bcb1d6-27f7-5e30-ae6b-7acb5ee94098
* Content: [Use Microsoft Edge with IE mode](https://docs.microsoft.com/en-us/DeployEdge/edge-ie-mode#feedback)
* Content Source: [edgeenterprise/edge-ie-mode.md](https://github.com/MicrosoftDocs/EdgeEnterprise-pr/blob/live/edgeenterprise/edge-ie-mode.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **kvice**

**Comment by shisub** [comment]
Thank you for the catch! Corrected the note.
