### ISSUE TITLE
Version which?

### ISSUE THREAD

**Issue by BR77BE** [MicrosoftDocs/EdgeEnterprise#22]
Why RS4 FFS?
Didn't that *codename* die 18 months ago?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8b8eb9e-ec36-c025-8fe9-f028c11ffa61
* Version Independent ID: d1a81437-f331-39f5-ffb5-0de7af702463
* Content: [Blocker Toolkit to disable automatic delivery of Microsoft Edge](https://docs.microsoft.com/en-au/deployedge/microsoft-edge-blocker-toolkit)
* Content Source: [edgeenterprise/microsoft-edge-blocker-toolkit.md](https://github.com/MicrosoftDocs/EdgeEnterprise-pr/blob/live/edgeenterprise/microsoft-edge-blocker-toolkit.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **kvice**

**Comment by dan-wesley** [comment]
Correct. It should be 1803. We'll update the article.
Thank you.

**Comment by BR77BE** [comment]
Now the first Overview paragraph says, "To help our customers become more secure and up-to-date, Microsoft will distribute Microsoft Edge (Chromium-based) to Home and Pro Edition devices running Windows 10 version 1803 via Windows Update." Shouldn't that say "1803 *and newer*" like the second paragraph?

**Comment by dan-wesley** [comment]
@BR77BE 
thank you for your feedback
