### ISSUE TITLE
Intune based config

### ISSUE THREAD

**Issue by thommck** [MicrosoftDocs/EdgeEnterprise#23]
Need documentation on configuring this for Azure AD only devices via Intune

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aae869a8-2ae4-d28f-6c85-c1190609f87b
* Version Independent ID: e2bcb1d6-27f7-5e30-ae6b-7acb5ee94098
* Content: [Use Microsoft Edge with IE mode](https://docs.microsoft.com/en-us/DeployEdge/edge-ie-mode)
* Content Source: [edgeenterprise/edge-ie-mode.md](https://github.com/MicrosoftDocs/EdgeEnterprise-pr/blob/live/edgeenterprise/edge-ie-mode.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **kvice**

**Comment by Simsen** [comment]
Yes - I have been testing this solution on AAD joined devices - and had some issue.
I have located the XML file locally on the client and made the policies.
But it is not clear to me if the policy should point to the XML file like this:
file:///c:/Users/<user>/Documents/sites.xml
OR
file:///c:\Users\<user>\Documents\sites.xml

**Comment by dan-wesley** [comment]
file:///c:/Users//Documents/sites.xml

**Comment by dan-wesley** [comment]
@Simsen 
Sorry about huge delay in responding, Please check out updated and reorganized IE mode docs at:
https://docs.microsoft.com/en-us/DeployEdge/edge-ie-mode
