### ISSUE TITLE
If it doesn't use ESR, does roaming need an Azure AD Premium licence, or not?

### ISSUE THREAD

**Issue by anwarmahmood1** [MicrosoftDocs/EdgeEnterprise#25]
Your article only mentions Azure AD account; it doesn't specify licences. please clear up this ambiguity. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa50920d-132e-8cda-02cb-1e887f3f9331
* Version Independent ID: c96f8bfd-4303-d750-3034-bfd5b0fcccc8
* Content: [Microsoft Edge and Enterprise State Roaming](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-enterprise-state-roaming#feedback)
* Content Source: [edgeenterprise/microsoft-edge-enterprise-state-roaming.md](https://github.com/MicrosoftDocs/EdgeEnterprise/blob/public/edgeenterprise/microsoft-edge-enterprise-state-roaming.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **kvice**

**Comment by justinfcoffey** [comment]
Sync requires Azure AD Premium for a work/school account. Not for a Microsoft (consumer) account. Reference https://docs.microsoft.com/en-us/DeployEdge/microsoft-edge-security-identity

**Comment by justinfcoffey** [comment]
And at least AIP P1 (or a subscription that includes it - i.e., Office 365 E3). Reference https://docs.microsoft.com/en-us/DeployEdge/microsoft-edge-enterprise-sync

**Comment by dan-wesley** [comment]
Also, check out Microsoft Edge and Enterprise State Roaming at https://docs.microsoft.com/en-us/DeployEdge/microsoft-edge-enterprise-state-roaming
