### ISSUE TITLE
Link to prevent automatic installation provides no useful information

### ISSUE THREAD

**Issue by BR77BE** [MicrosoftDocs/EdgeEnterprise#26]
"1. Prevent the automatic install of the next version of Microsoft Edge by Windows Update. For more information, see Windows Update: FAQ"

Windows Update FAQ does not explain how to prevent the automatic installation of the next version of Microsoft Edge.

A link should instead be provided to Blocker Toolkit to disable automatic delivery of Microsoft Edge;
https://docs.microsoft.com/en-us/deployedge/microsoft-edge-blocker-toolkit

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d96bfa14-a7be-f140-f914-564fe81c94e8
* Version Independent ID: 8343f63e-b2e4-27bc-11ad-3db51c4e3f03
* Content: [Access the old version of Microsoft Edge](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-sysupdate-access-old-edge)
* Content Source: [edgeenterprise/microsoft-edge-sysupdate-access-old-edge.md](https://github.com/MicrosoftDocs/EdgeEnterprise/blob/public/edgeenterprise/microsoft-edge-sysupdate-access-old-edge.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **jtkim**

**Comment by woody30r0** [comment]
Same issue here. There is not the slightest information regarding "Prevent the automatic install of the next version of Microsoft Edge by Windows Update" in the Windows Update FAQ.

**Comment by woody30r0** [comment]
And what do you mean with "This side-by-side solution is less complex and requires less management that the detailed solution described next in this article." What solution should be less complex and with less management than setting a single GPO entry, I'd really like to see that, please?

**Comment by dan-wesley** [comment]
@BR77BE @woody30r0 
The Microsoft Edge docs were updated. Are they more in line with what you're looking for?
See node, System Updates for Microsoft Edge. First article in node is https://docs.microsoft.com/en-us/DeployEdge/microsoft-edge-blocker-toolkit.
Thanks

**Comment by woody30r0** [comment]
Yes, the link is there and that article contains all required information now. Thanks.
