### ISSUE TITLE
Edge administrative templates required before Group Policy changes

### ISSUE THREAD

**Issue by CarlTuckerson** [MicrosoftDocs/EdgeEnterprise#27]
I had no "Microsoft Edge Update" administrative template in the group policy editor. I found it necessary to download the Edge administrative templates at https://www.microsoftedgeinsider.com/en-us/enterprise, then follow the instructions to "Add the administrative template to an individual computer" found at https://docs.microsoft.com/en-us/deployedge/configure-microsoft-edge (substituting msedgeupdate for msedge). THEN I could make the necessary change with the group policy editor.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d96bfa14-a7be-f140-f914-564fe81c94e8
* Version Independent ID: 8343f63e-b2e4-27bc-11ad-3db51c4e3f03
* Content: [Access the old version of Microsoft Edge](https://docs.microsoft.com/en-au/deployedge/microsoft-edge-sysupdate-access-old-edge)
* Content Source: [edgeenterprise/microsoft-edge-sysupdate-access-old-edge.md](https://github.com/MicrosoftDocs/EdgeEnterprise/blob/public/edgeenterprise/microsoft-edge-sysupdate-access-old-edge.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **jtkim**

**Comment by linkingjj** [comment]
You are right, but after I add the administrative template, I still cannot see the "Microsoft Edge Update". I think I have to install Microsoft Edge with Chromium first? Did you see the "Microsoft Edge Update" administrative template in the group policy editor after you add the "MicrosoftEdgePolicyTemplates"?

**Comment by tomasprieboj** [comment]
For me, I can't see "Applications" option. Any ideas?

**Comment by linkingjj** [comment]
Did  you also put "msedgeupdate.admx" and "msedgeupdate.adml" into PolicyDefinitions folder?

**Comment by detlefs** [comment]
Microsoft Edge Update node only appeared after rebooting the machine. So, if you don't see it, try a reboot...
