### ISSUE TITLE
macOS Support

### ISSUE THREAD

**Issue by built2order** [MicrosoftDocs/EdgeEnterprise#28]
There is no information (to the affirmative or negative) regarding support for macOS devices.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aae869a8-2ae4-d28f-6c85-c1190609f87b
* Version Independent ID: e2bcb1d6-27f7-5e30-ae6b-7acb5ee94098
* Content: [Use Microsoft Edge with IE mode](https://docs.microsoft.com/en-us/DeployEdge/edge-ie-mode#feedback)
* Content Source: [edgeenterprise/edge-ie-mode.md](https://github.com/MicrosoftDocs/EdgeEnterprise/blob/public/edgeenterprise/edge-ie-mode.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **kvice**

**Comment by prbsparx** [comment]
I'm also curious about this. Would love to know if it exists.

**Comment by dan-wesley** [comment]
@built2order @prbsparx 
Microsoft Edge supported operating systems: https://docs.microsoft.com/en-us/DeployEdge/microsoft-edge-supported-operating-systems
