### ISSUE TITLE
Missing Windows 10 1909

### ISSUE THREAD

**Issue by hypercube33** [MicrosoftDocs/EdgeEnterprise#29]
The above document does not include anything for 1909

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 133b101b-6853-71c1-25f8-1fae40665ab7
* Version Independent ID: 5104a461-8c49-9f1c-c3cb-dce34c7e5fa1
* Content: [Windows updates for Microsoft Edge](https://docs.microsoft.com/en-us/DeployEdge/microsoft-edge-sysupdate-windows-updates#feedback)
* Content Source: [edgeenterprise/microsoft-edge-sysupdate-windows-updates.md](https://github.com/MicrosoftDocs/EdgeEnterprise/blob/public/edgeenterprise/microsoft-edge-sysupdate-windows-updates.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **jtkim**

**Comment by dan-wesley** [comment]
@hypercube33 this document was updated in Feb 2020
