### ISSUE TITLE
Clarify options of blocking Chromium Edge

### ISSUE THREAD

**Issue by ryeguy637** [MicrosoftDocs/EdgeEnterprise#31]
The overview states "Organizations can use those products to fully manage deployment of updates released through Windows Update and Microsoft Update, including Microsoft Edge (Chromium-based), within their environment.". Does this mean that new Chromium Edge will be a discrete update in WSUS after January patches are released?  Or will the new Edge be bundled within the January Cumulative Update for Win10.  If bundled in the cumulative update, then organizations cannot really rely on WSUS to control the Edge upgrade.

I assume I'm not the only one trying to quickly figure out if we want to delay Chromium Edge and whether we should deploy the registry-based group preference or assume it will be a separate patch in the WSUS console (that we can not approve)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8b8eb9e-ec36-c025-8fe9-f028c11ffa61
* Version Independent ID: d1a81437-f331-39f5-ffb5-0de7af702463
* Content: [Blocker Toolkit to disable automatic delivery of Microsoft Edge](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-blocker-toolkit#feedback)
* Content Source: [edgeenterprise/microsoft-edge-blocker-toolkit.md](https://github.com/MicrosoftDocs/EdgeEnterprise/blob/public/edgeenterprise/microsoft-edge-blocker-toolkit.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **kvice**

**Comment by dan-wesley** [comment]
Thank you for the feedback.
The new Microsoft Edge update will be stand-alone and not part of any cumulative updates. Hope this helps.
Dan

**Comment by ryeguy637** [comment]
It does help.  Thanks for the clarification.
Ryan

**Comment by Trooper27** [comment]
Yes thank you very much Dan. I was about to post something similar here as we use WSUS at my job and was wondering if I needed to do anything drastic to block it.  We are likely going to approve it for a small user base to test at first, then if all is well go with the full rollout.

Cheers and Happy New Year!

**Comment by marypcbuk** [comment]
can't seem to open a new issue for this page here or on GitHub, so tagging on to the end to ask for a section on troubleshooting the tool when you get the "access denied" error message

**Comment by marypcbuk** [comment]
(the solution being 'run as admin' of course, but helpful to say so)

**Comment by dan-wesley** [comment]
@marypcbuk  Will pass this on. @appcompatguy

**Comment by appcompatguy** [comment]
@marypcbuk While we are trying to detect this and elevate to get user installs working, I don't know that we have enough coverage to document this as supported. We still recommend installing at system level to use enterprise features (and if you're managing IE mode, we expect you're also managing the install). But let me pass on the feedback to the team, because when these docs were written, we didn't have any way to work at all for a user install, and I don't know if the intent is to make this a supported scenario. Thanks for the feedback!

**Comment by marypcbuk** [comment]
@appcompatguy if I'm running it on a local machine, I might be the admin walking up to the user's machine and running the blocker command from a USB or file share, and while good practice would be not to just sit down and use their account, it's going to happen (or they might be the rare admin who isn't logged in as admin all the time!). it stumped me for 5 minutes ;)

**Comment by appcompatguy** [comment]
@marypcbuk Got it - we've added this to the backlog for the next doc update! Thanks for pointing this out!

**Comment by PaulKlerkx** [comment]
Hi,
    Can I get some clarification - Our company wants to test new edge for a few months before deploying to all computers.  
We use MECM with an Automatic deployment Rule (ADR) that includes Microsoft Edge.  We are on Windows 10.1809.
Basically my question is will an ADR which included MS Edge UPGRADE Edge (to new edge) or just UPDATE edge (whether old or new version)
  Do I
1. use the blocker to block upgrading to new edge, but still allow old edge updates
2. use the blocker to block upgrading to new edge and my old edge will also stop updating.  
3. don't need the blocker and my old edge updates will continue but new edge won't deploy till I use the MECM deployment of New Edge.

**Comment by appcompatguy** [comment]
@PaulKlerkx - if you are managing your Windows Updates, then you do not need to target with the blocker toolkit. Details are in the blocker toolkit docs: https://docs.microsoft.com/en-us/deployedge/microsoft-edge-blocker-toolkit#overview
