### ISSUE TITLE
How to block update using intune

### ISSUE THREAD

**Issue by wbach82** [MicrosoftDocs/EdgeEnterprise#34]
is it possible to block the update on intune managed devices like custom profile (ADMX ingest) or administrative template profile?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8b8eb9e-ec36-c025-8fe9-f028c11ffa61
* Version Independent ID: d1a81437-f331-39f5-ffb5-0de7af702463
* Content: [Blocker Toolkit to disable automatic delivery of Microsoft Edge](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-blocker-toolkit)
* Content Source: [edgeenterprise/microsoft-edge-blocker-toolkit.md](https://github.com/MicrosoftDocs/EdgeEnterprise/blob/public/edgeenterprise/microsoft-edge-blocker-toolkit.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **kvice**

**Comment by repmeer** [comment]
Thomas Kurth wrote a powershell script to block and unblock edge chromium
https://www.wpninjas.ch/2019/12/be-prepared-the-chromium-based-edge-will-be-released-in-january/

**Comment by thbch** [comment]
See the comment of Sean there - still waiting on clarifying documentation about this, if Edge is now really distributed next week!
"If a device is managed by Windows Update for Business, is MDM-managed, is volume-licensed or is an Enterprise, Education or Server SKU, it will not be targeted for automatic rollout and the blocker toolkit is not required. The blocker toolkit is only required on devices that don’t meet the criteria above. We will update the blocker toolkit docs to make that clear and will publish additional documentation in the new year.
– Sean Lyndersay (Microsoft Edge team)"

**Comment by wbach82** [comment]
really looking forward to see an updated article.... the release is next week and no complete documentation about how to block and evene if blocking is possible or required.

**Comment by PeterKlapwijk** [comment]
The article now states "Organizations with updates managed through Windows Update for Business (WUfB) will not automatically receive this update and do not need to deploy the blocker toolkit."
So when you use Intune to control the updates via WUfB, the new Edge browser is not automatically deployed. But what is the recommended way to deploy the browser to Intune managed clients?

**Comment by appcompatguy** [comment]
@PeterKlapwijk - if you are using Microsoft Intune, we have invested in a first-class experience for deploying the new Microsoft Edge. Documentation is here: https://docs.microsoft.com/en-us/intune/apps/apps-windows-edge?toc=https://docs.microsoft.com/DeployEdge/toc.json&bc=https://docs.microsoft.com/DeployEdge/breadcrumb/toc.json

**Comment by PeterKlapwijk** [comment]
Thanks for the confirmation!
