### ISSUE TITLE
link to tools/templates

### ISSUE THREAD

**Issue by marypcbuk** [MicrosoftDocs/EdgeEnterprise#36]
suggest adding a link to the Blocker Toolkit and ADMX template downloads  (https://docs.microsoft.com/en-us/deployedge/microsoft-edge-blocker-toolkit) on this page

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d96bfa14-a7be-f140-f914-564fe81c94e8
* Version Independent ID: 8343f63e-b2e4-27bc-11ad-3db51c4e3f03
* Content: [Access the old version of Microsoft Edge](https://docs.microsoft.com/en-gb/deployedge/microsoft-edge-sysupdate-access-old-edge#feedback)
* Content Source: [edgeenterprise/microsoft-edge-sysupdate-access-old-edge.md](https://github.com/MicrosoftDocs/EdgeEnterprise/blob/public/edgeenterprise/microsoft-edge-sysupdate-access-old-edge.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **jtkim**

**Comment by dan-wesley** [comment]
Good idea, will pass it on.
Thank you.
