### ISSUE TITLE
Completely different, and much easier process available - this needs updating

### ISSUE THREAD

**Issue by domcote** [MicrosoftDocs/EdgeEnterprise#37]
NEW: Sign in to Endpoint Manager --&gt; Apps --&gt; All Apps --&gt; +Add --&gt; App type --&gt; "Microsoft Edge..."/Windows 10. Configure App Information etc. Assign to Users - even mandatory install possible. Done! Super easy, super simple.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 313f5f2b-7884-7a91-cc1d-72f45c751d67
* Version Independent ID: e40a3da6-9f30-c9b1-0c1a-29f65ddccb65
* Content: [Deploy Microsoft Edge for Windows 10 using Microsoft Intune](https://docs.microsoft.com/en-us/deployedge/deploy-edge-with-intune?source=docs#feedback)
* Content Source: [edgeenterprise/deploy-edge-with-intune.md](https://github.com/MicrosoftDocs/EdgeEnterprise/blob/public/edgeenterprise/deploy-edge-with-intune.md)
* Product: **microsoft-edge**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by dan-wesley** [comment]
@domcote Thank you for providing this information. Much appreciated.
Have you looked at the updated (April) documentation?
https://docs.microsoft.com/en-us/mem/intune/apps/apps-windows-edge?toc=https%3A%2F%2Fdocs.microsoft.com%2FDeployEdge%2Ftoc.json&bc=https%3A%2F%2Fdocs.microsoft.com%2FDeployEdge%2Fbreadcrumb%2Ftoc.json
