### ISSUE TITLE
stable release code

### ISSUE THREAD

**Issue by nb-ofs** [MicrosoftDocs/EdgeEnterprise#40]
if beta is MSEdgeBHTML and dev MSEdgeDHTML, what is the stable release?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d80a2f5-5b21-a16b-c401-5e1c40be6f00
* Version Independent ID: b63c5b42-443b-687c-a445-58fa4de6b84b
* Content: [Set Microsoft Edge as the default browser on Windows and macOS](https://docs.microsoft.com/en-gb/DeployEdge/edge-default-browser)
* Content Source: [edgeenterprise/edge-default-browser.md](https://github.com/MicrosoftDocs/EdgeEnterprise/blob/public/edgeenterprise/edge-default-browser.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **brianalt**

**Comment by win2000b** [comment]
MSEdgeHTM. They have updated the article now the stable version is out

**Comment by dan-wesley** [comment]
@nb-ofs 
- channel docs: https://docs.microsoft.com/en-us/DeployEdge/microsoft-edge-channels
- stable channel release notes https://docs.microsoft.com/en-us/DeployEdge/microsoft-edge-relnote-stable-channel
