### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by nalhemyariirexorg** [MicrosoftDocs/EdgeEnterprise#41]
If 'Devices running Windows 10 Home or Pro Edition that are joined to an Active Directory or Azure Active Directory domain, are MDM managed, or are WSUS or WUfB managed, will also be excluded from this automatic update.' then what is the use of the gp admin template in this page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8b8eb9e-ec36-c025-8fe9-f028c11ffa61
* Version Independent ID: d1a81437-f331-39f5-ffb5-0de7af702463
* Content: [Blocker Toolkit to disable automatic delivery of Microsoft Edge](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-blocker-toolkit#feedback)
* Content Source: [edgeenterprise/microsoft-edge-blocker-toolkit.md](https://github.com/MicrosoftDocs/EdgeEnterprise/blob/public/edgeenterprise/microsoft-edge-blocker-toolkit.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **kvice**

**Comment by BR77BE** [comment]
For any Pro edition not joined to AD, MDM, WSUS etc., of which there are plenty.
