### ISSUE TITLE
ManagedSearchEngines image_search_url required?

### ISSUE THREAD

**Issue by oleesch** [MicrosoftDocs/EdgeEnterprise#44]
The documentation states that "You do not need to specify the encoding, suggest_url, image_search_url, or image_search_post_params for any search engine".

Either the documentation is wrong or the product has a bug because if I omit image_search_url from any single search engine definition, the browser will ignore the whole JSON. Using Edge Stable 79.0.309.65 on Windows 10 1809.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1cd3ad5-bb4a-54ff-84e7-18ca0b11368f
* Version Independent ID: 984abd8f-45eb-737b-ad74-07ec8261f9eb
* Content: [Microsoft Edge Browser Policy Documentation](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#feedback)
* Content Source: [edgeenterprise/microsoft-edge-policies.md](https://github.com/MicrosoftDocs/EdgeEnterprise/blob/public/edgeenterprise/microsoft-edge-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @Brianalt-Msft
* Microsoft Alias: **stmoody**

**Comment by Brianalt-Msft** [comment]
Thank your for reporting this. I've logged a bug with our search team.

**Comment by mickeybyte** [comment]
Has anyone succeeded in setting the ManagedSearchEngines correctly? Whatever I try to put in there, it always ends up with an error (can be checked using the URL: edge://policy). 
I even tried the example provided on this page and it didn't accept it! 

I tried following example and the error is "Value doesn't match expected format."

[ {"is_default": true,"keyword": "Google","name": "Google","search_url": "https://www.google.com/search?q={searchTerms}","image_search_url": "https://www.google.com/search?tbm=isch&q={searchTerms}"}, {"is_default": false,"keyword": "DuckDuckGo","name": "DuckDuckGo","search_url": "https://duckduckgo.com/?q={searchTerms}","image_search_url": "https://duckduckgo.com/?iax=images&ia=images&q={searchTerms}"} ]

A working expample would be very much appreciated.

**Comment by oleesch** [comment]
This is the one I'm currently using that is accepted by the browser (flattened to one line of course):

`[
    {
        "name": "Google",
        "keyword": "google.ch",
        "is_default": true,
        "search_url": "{google:baseURL}search?q={searchTerms}&{google:RLZ}{google:originalQueryForSuggestion}{google:assistedQueryStats}{google:searchFieldtrialParameter}{google:searchClient}{google:sourceId}ie={inputEncoding}",
        "suggest_url": "{google:baseURL}complete/search?output=chrome&q={searchTerms}",
        "image_search_url": "{google:baseURL}searchbyimage/upload"
    },
    {
        "name": "Bing",
        "keyword": "bing.com",
        "search_url": "{bing:baseURL}search?q={searchTerms}",
        "suggest_url": "{bing:baseURL}qbox?query={searchTerms}",
        "image_search_url": "{bing:baseURL}images/detail/search?iss=sbiupload&FORM=ANCMS1#enterInsights"
    },
    {
        "name": "DuckDuckGo",
        "keyword": "duckduckgo.com",
        "search_url": "https://duckduckgo.com/?q={searchTerms}",
        "suggest_url": "https://duckduckgo.com/ac/?q={searchTerms}&type=list",
        "image_search_url": "{google:baseURL}searchbyimage/upload"
    },
    {
        "name": "Ecosia",
        "keyword": "ecosia.org",
        "search_url": "https://www.ecosia.org/search?q={searchTerms}&addon=opensearch",
        "suggest_url": "https://ac.ecosia.org/autocomplete?q={searchTerms}&type=list",
        "image_search_url": "{google:baseURL}searchbyimage/upload"
    },
    {
        "name": "Yahoo! Schweiz",
        "keyword": "ch.yahoo.com",
        "search_url": "https://ch.search.yahoo.com/search{google:pathWildcard}?ei={inputEncoding}&fr=crmas&p={searchTerms}",
        "suggest_url": "https://ch.search.yahoo.com/sugg/chrome?output=fxjson&appid=crmas&command={searchTerms}",
        "image_search_url": "{google:baseURL}searchbyimage/upload"
    }
]`

Are you sure that the DuckDuckGo image search URL you're using is correct? I was under the impression this was a POST request without any search terms. At least that's what I guessed by looking at the [Chromium defaults](https://github.com/chromium/chromium/blob/master/components/search_engines/prepopulated_engines.json). Happy to be corrected though.

**Comment by mickeybyte** [comment]
I'm gonne try this and update with the results. 
About DuckDuckGo, if you go to https://duckduckgo.com/?iax=images&ia=images&q=DuckDuckGo you'll get the image results, so I'm guessing this is a correct way?

**Comment by mickeybyte** [comment]
I can confirm the above setting for ManagedSearchEngines works fine. 

This also confirms that the documentation is not correct, saying not all fields are required...

**Comment by narutards** [comment]
I can confirm that the following JSON works:

`[ 
 { 
  "name": "Google", 
  "keyword": "Google", 
  "is_default": true, 
  "search_url": "https://www.google.de/search?q={searchTerms}", 
  "image_search_url": "https://www.google.de/search?q={searchTerms}&tbm=isch",
  "suggest_url": "https://www.google.de/complete/search?q={searchTerms}&output=chrome"

 }, 
 { 
  "name": "DuckDuckGo", 
  "keyword": "DuckDuckGo", 
  "is_default": false, 
  "search_url": "https://duckduckgo.com/?q={searchTerms}", 
  "image_search_url": "https://duckduckgo.com/?q={searchTerms}&iax=images&ia=images",
  "suggest_url": "https://duckduckgo.com/ac/?q={searchTerms}&type=list"
 } 
]`

I had to add both "image_search_url" and "suggest_url" to make it work. Without them Edge would complain that the JSON was not in the expected format.

**Comment by dmutsaers** [comment]
{ "name": "Yahoo! Schweiz", "keyword": "ch.yahoo.com", "search_url": "https://ch.search.yahoo.com/search{google:pathWildcard}?ei={inputEncoding}&fr=crmas&p={searchTerms}", "suggest_url": "https://ch.search.yahoo.com/sugg/chrome?output=fxjson&appid=crmas&command={searchTerms}", "image_search_url": "{google:baseURL}searchbyimage/upload" } ]

Isn't there a typo? Shouldn't **ei**={inputEncoding} be changed in **ie**={inputEncoding}

**Comment by dmutsaers** [comment]
Also, somehow the Google keyword changes to "google.com_", no matter what I configure in the json string. Anyone else seeing this behaviour?

Best regards,
Dennis.

**Comment by oleesch** [comment]
@dmutsaers 
I've got those Yahoo URLs directly from the [Chromium repo](https://github.com/chromium/chromium/blob/master/components/search_engines/prepopulated_engines.json). Unfortunately I can't find any reference by Yahoo so for now I'll trust that **ei** is correct.

Regarding the underscore, I don't see that issue on my end. Are you sure you're not somehow configuring google.com more than once?

**Comment by dmutsaers** [comment]
@oleesch 
You're probably right to assume that "ei" is right.

I think the _ underscore happens when the user has configured Google as default before the GPO has bee applied. Not sure about that, though.

**Comment by byron-edmonds** [comment]
In my experience with this policy including the image_search_url parameter in each search provider but with an empty string worked fine:
[  {    "suggest_url": "https://www.google.com.au/complete/search?output=chrome&q={searchTerms}",     "image_search_url": "",     "name": "Google",     "keyword": "google",     "is_default": true,     "search_url": "https://www.google.com.au/search?q={searchTerms}"  },   {    "image_search_url": "",     "suggest_url": "https://www.bing.com/qbox?query={searchTerms}",     "search_url": "https://www.bing.com/search?q={searchTerms}",     "name": "Bing",     "keyword": "bing"  },   {    "suggest_url": "https://ac.ecosia.org/autocomplete?q={searchTerms}&type=list",     "image_search_url": "",     "name": "Ecosia",     "keyword": "ecosia",     "search_url": "https://www.ecosia.org/search?q={searchTerms}"  }]

**Comment by amtsa** [comment]
The suggest_url and image_search_url parameters will be optional in Edge 80. In the meantime, you can use an empty string. The image_search_post_params parameter will be available and optional in Edge 80.
