### ISSUE TITLE
RoamingProfileSupportEnabled does not exist

### ISSUE THREAD

**Issue by oleesch** [MicrosoftDocs/EdgeEnterprise#45]
The policy "SyncDisabled" references another policy called "RoamingProfileSupportEnabled". As far as I can tell that policy doesn't exist (can't find it anywhere in the ADMX files or on this page).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1cd3ad5-bb4a-54ff-84e7-18ca0b11368f
* Version Independent ID: 984abd8f-45eb-737b-ad74-07ec8261f9eb
* Content: [Microsoft Edge Browser Policy Documentation](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#feedback)
* Content Source: [edgeenterprise/microsoft-edge-policies.md](https://github.com/MicrosoftDocs/EdgeEnterprise/blob/public/edgeenterprise/microsoft-edge-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @Brianalt-Msft
* Microsoft Alias: **stmoody**

**Comment by Brianalt-Msft** [comment]
Thank you for raising this issue. This is a bug in our documentation. We currently do not support this policy.

**Comment by Brianalt-Msft** [comment]
This has been fixed.
