### ISSUE TITLE
NewTabPageLocation not working as recommend

### ISSUE THREAD

**Issue by jasminrueegger** [MicrosoftDocs/EdgeEnterprise#49]
NewTabPageLocation in Recommened Settings blocks user changes as well. Seems to be a bug.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1cd3ad5-bb4a-54ff-84e7-18ca0b11368f
* Version Independent ID: 984abd8f-45eb-737b-ad74-07ec8261f9eb
* Content: [Microsoft Edge Browser Policy Documentation](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#feedback)
* Content Source: [edgeenterprise/microsoft-edge-policies.md](https://github.com/MicrosoftDocs/EdgeEnterprise/blob/public/edgeenterprise/microsoft-edge-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @Brianalt-Msft
* Microsoft Alias: **stmoody**

**Comment by Brianalt-Msft** [comment]
I've shared this with our New Tab Page feature team.

**Comment by jasminrueegger** [comment]
Same problem with "Action to take on startup". The "sites to open when the browser starts" are customizable by the user, but the action cannot be changed even though both settings are in "Microsft Edge - Default Settings (user can override)"

**Comment by jasminrueegger** [comment]
With RestoreOnStartupURLs the setting just seems to be set at the wrong place in the registry. Manually moving it to the Recommended key seems to work. 
But NetTabPageLocation is set under Recommended but is still enforced.
