### ISSUE TITLE
Some DWORD example value's contain True instead of 1

### ISSUE THREAD

**Issue by FreekBloemhof** [MicrosoftDocs/EdgeEnterprise#5]
Not sure if this is the right place to mention this, but scanning al the configurations in the policy reference I saw that some example values are referenced wrong.

By example: https://docs.microsoft.com/en-us/DeployEdge/microsoft-edge-policies#allowdeletingbrowserhistory

**Comment by shisub** [comment]
Thank you for the feedback. This has been corrected.
