### ISSUE TITLE
RestoreOnStartupURLs and RestoreOnStartup are missing

### ISSUE THREAD

**Issue by jasminrueegger** [MicrosoftDocs/EdgeEnterprise#51]
These GPOs are documented but do not exist.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1cd3ad5-bb4a-54ff-84e7-18ca0b11368f
* Version Independent ID: 984abd8f-45eb-737b-ad74-07ec8261f9eb
* Content: [Microsoft Edge Browser Policy Documentation](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#restoreonstartupurls)
* Content Source: [edgeenterprise/microsoft-edge-policies.md](https://github.com/MicrosoftDocs/EdgeEnterprise/blob/public/edgeenterprise/microsoft-edge-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @Brianalt-Msft
* Microsoft Alias: **stmoody**

**Comment by Brianalt-Msft** [comment]
In GP editor RestoreOnStartup is "Action to take on startup" and RestoreOnStartupURLs is "Sites to open when the browser starts". Both are in the "Startup, home page and new tab page policies" folder.
