### ISSUE TITLE
Hybrid Environment = "on-prem accounts" ?

### ISSUE THREAD

**Issue by rdspivot** [MicrosoftDocs/EdgeEnterprise#52]
Re this notation:

_What about sync support for on-prem accounts?
Currently Microsoft Edge doesn't support sync for on-prem accounts. We will be adding this support in a future release._

Does "on prem account" include an AAD account whose source is Windows Server AD (on-premises, sync'd through Azure AD Connect?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ca3f20e-22b7-2d5a-67eb-0da9d27dcde8
* Version Independent ID: 7f6980c3-ce44-f0bc-fd76-bdf8cb7938b5
* Content: [Microsoft Edge Sync](https://docs.microsoft.com/en-us/DeployEdge/microsoft-edge-enterprise-sync#feedback)
* Content Source: [edgeenterprise/microsoft-edge-enterprise-sync.md](https://github.com/MicrosoftDocs/EdgeEnterprise/blob/public/edgeenterprise/microsoft-edge-enterprise-sync.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **kvice**

**Comment by mike-yam** [comment]
> Re this notation:
> 
> _What about sync support for on-prem accounts? Currently Microsoft Edge doesn't support sync for on-prem accounts. We will be adding this support in a future release._
> 
> Does "on prem account" include an AAD account whose source is Windows Server AD (on-premises, sync'd through Azure AD Connect?)
> 
> #### Document Details
> ⚠ _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._
> 
> * ID: 3ca3f20e-22b7-2d5a-67eb-0da9d27dcde8
> * Version Independent ID: 7f6980c3-ce44-f0bc-fd76-bdf8cb7938b5
> * Content: [Microsoft Edge Sync](https://docs.microsoft.com/en-us/DeployEdge/microsoft-edge-enterprise-sync#feedback)
> * Content Source: [edgeenterprise/microsoft-edge-enterprise-sync.md](https://github.com/MicrosoftDocs/EdgeEnterprise/blob/public/edgeenterprise/microsoft-edge-enterprise-sync.md)
> * Product: **microsoft-edge**
> * GitHub Login: @dan-wesley
> * Microsoft Alias: **kvice**

Same here. Our users log in Windows using on-prem AD account. Is there any policy that enforce user sync in their Azure account in Edge, instead of on-prem AD account? (We have ADFS)

**Comment by colemoine** [comment]
think this is coming with version 81:
https://docs.microsoft.com/en-us/deployedge/microsoft-edge-relnote-beta-channel#version-81041612-february-20

On-prem Active Directory account auto sign in will only be targeted to organizations that turn it on. If users were already signed in with an on-prem AD account, they will now be able to sign out of it. Now, users will only be automatically signed in with the primary account on their operating system if it is an MSA or an Azure AD account. Admins can enable auto sign in with an on-prem AD account using the ConfigureOnPremisesAccountAutoSignIn policy.
