### ISSUE TITLE
TargetVersion Policy Request

### ISSUE THREAD

**Issue by iviikel** [MicrosoftDocs/EdgeEnterprise#54]
Edge Chromium is one step away from replacing Google Chrome in my organization except it's missing one crucial policy that Google has provided "TargetVersionPrefix". This policy allows you to control exactly what version is installed via Web download or auto-update and ensures all users are running the exact version you want them to regardless of the source. It also allows you to easily test new versions only for certain groups and makes rolling out updates as easy as updating one single policy in your domain. Please add this policy item!!!

Chrome example config

Key: Software\Policies\Google\Update\TargetVersionPrefix{8A69D345-D564-463C-AFF1-A69D9E530F96} Value: 73. 
Key: Software\Policies\Google\Update\Update{8A69D345-D564-463C-AFF1-A69D9E530F96} Value: 1 
Key: Software\Policies\Google\Update\Update{C4D65027-B96A-49A5-B13C-4E7FAFD2FB7B} Value: 0 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1cd3ad5-bb4a-54ff-84e7-18ca0b11368f
* Version Independent ID: 984abd8f-45eb-737b-ad74-07ec8261f9eb
* Content: [Microsoft Edge Browser Policy Documentation](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#feedback)
* Content Source: [edgeenterprise/microsoft-edge-policies.md](https://github.com/MicrosoftDocs/EdgeEnterprise/blob/public/edgeenterprise/microsoft-edge-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @Brianalt-Msft
* Microsoft Alias: **stmoody**

**Comment by Brianalt-Msft** [comment]
@iviikel Thank you for letting us know. This policy is in our backlog and I've shared your feedback with the feature team.
