### ISSUE TITLE
DefaultInsecureContentSetting indicates integer values but not what they mean

### ISSUE THREAD

**Issue by apizz** [MicrosoftDocs/EdgeEnterprise#56]
The example only indicates an integer value of '2'.  But what does this setting mean within the context of this setting?  Is there also '0' and '1' value options?  If so, what do they mean?

https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#defaultinsecurecontentsetting

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1cd3ad5-bb4a-54ff-84e7-18ca0b11368f
* Version Independent ID: 984abd8f-45eb-737b-ad74-07ec8261f9eb
* Content: [Microsoft Edge Browser Policy Documentation](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#feedback)
* Content Source: [edgeenterprise/microsoft-edge-policies.md](https://github.com/MicrosoftDocs/EdgeEnterprise/blob/public/edgeenterprise/microsoft-edge-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @Brianalt-Msft
* Microsoft Alias: **stmoody**

**Comment by Brianalt-Msft** [comment]
@apizz I've raised this with the feature team.

**Comment by Brianalt-Msft** [comment]
@apizz There are only two possible values:
name: 'BlockInsecureContent',
          value: 2 = Do not allow any site to load blockable mixed content
name: 'AllowExceptionsInsecureContent',
          value: 3 = Allow users to add exceptions to allow blockable mixed content
