### ISSUE TITLE
Opening Files from Mapped Drives using file:/// URL

### ISSUE THREAD

**Issue by eximo84** [MicrosoftDocs/EdgeEnterprise#58]
So we host a HTML page internally that links to a bunch of RRD files (crystal reports).  In IE users can click a link to these RRD files hosted on a mapped drive. The url is example: file:///R:/Reports/SalesReport.rrd

In IE11 this opens the application associated with RRD extension however in chrome the contents of the RRD is displayed instead.  Using IE mode in new Edge i assumed it would follow what IE 11 does however it doesnt and the behaviour i see is the same as default Chrome.  I assumes its due to NPAPI that was removed from chrome some time ago.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aae869a8-2ae4-d28f-6c85-c1190609f87b
* Version Independent ID: e2bcb1d6-27f7-5e30-ae6b-7acb5ee94098
* Content: [Use Microsoft Edge with IE mode](https://docs.microsoft.com/en-us/deployedge/edge-ie-mode#feedback)
* Content Source: [edgeenterprise/edge-ie-mode.md](https://github.com/MicrosoftDocs/EdgeEnterprise/blob/public/edgeenterprise/edge-ie-mode.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **kvice**

**Comment by shisub** [comment]
@eximo84 If you want the RRD files to behave as they do in IE11, you can enable IE mode integration and add the the destination URL to the Enterprise Mode Site List as described in the article. Otherwise, you will get the same behavior in Microsoft Edge as you see with Chrome.
