### ISSUE TITLE
Extendable startpage list

### ISSUE THREAD

**Issue by jasminrueegger** [MicrosoftDocs/EdgeEnterprise#60]
I'm missing the option to set a list of mandatory start pages which can be extended by the users. Before there was the policy "Disable lockdown of Start pages" which enabled this behavior.
Are there plans to bring this back in a future version?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1cd3ad5-bb4a-54ff-84e7-18ca0b11368f
* Version Independent ID: 984abd8f-45eb-737b-ad74-07ec8261f9eb
* Content: [Microsoft Edge Browser Policy Documentation](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies?source=docs#feedback)
* Content Source: [edgeenterprise/microsoft-edge-policies.md](https://github.com/MicrosoftDocs/EdgeEnterprise/blob/public/edgeenterprise/microsoft-edge-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @Brianalt-Msft
* Microsoft Alias: **stmoody**

**Comment by Brianalt-Msft** [comment]
@jasminrueegger Use the recommended version of [RestoreOnStartupURLs](https://docs.microsoft.com/deployedge/microsoft-edge-policies#restoreonstartupurls). The third paragraph in the intro of the [Configure Microsoft Edge for Windows](https://docs.microsoft.com/deployedge/configure-microsoft-edge#configure-policy-settings-on-windows) article explains mandatory vs recommended policy.
