### ISSUE TITLE
Spellcheck Languages

### ISSUE THREAD

**Issue by jasminrueegger** [MicrosoftDocs/EdgeEnterprise#63]
The spellcheck policy neither installs a language nor switches to the already installed chosen language. This policy does not seem to do anything (even tough the edge://policy/ page lists status as ok).
Tested with language en-GB (which is installed already) and hu (which is not)
active language always remains German.

Also, why is it not possible to install/use other languages than the few listed as supported? We would like to set "German (Switzerland)" so de-CH since this is the language our users write in. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1cd3ad5-bb4a-54ff-84e7-18ca0b11368f
* Version Independent ID: 984abd8f-45eb-737b-ad74-07ec8261f9eb
* Content: [Microsoft Edge Browser Policy Documentation](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies?source=docs#feedback)
* Content Source: [edgeenterprise/microsoft-edge-policies.md](https://github.com/MicrosoftDocs/EdgeEnterprise/blob/public/edgeenterprise/microsoft-edge-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @Brianalt-Msft
* Microsoft Alias: **stmoody**

**Comment by Brianalt-Msft** [comment]
@jasminrueegger Thank you for reporting. I've logged a bug for the feature team.

**Comment by gked** [comment]
> Also, why is it not possible to install/use other languages than the few listed as supported? We would like to set "German (Switzerland)" so de-CH since this is the language our users write in.

@jasminrueegger It is a limitation on hunspell (proofing tech that is used on Chromium-based browsers). Edge is shipping integration with Windows Speller which supports bunch more languages then hunspell. It's already in Canary and Dev channels and should be available in 81 stable. Although, it would not be available on Win 7.
