### ISSUE TITLE
Documentation missing about automatic task-bar pin and desktop shortcut creation in Windows

### ISSUE THREAD

**Issue by wesleyan-ablackburn** [MicrosoftDocs/EdgeEnterprise#64]
I have been trying new Edge for enterprise. I noticed that Edge pins itself to the current user's task bar as well as any new user profiles that are created after Edge is installed. I have looked around the new Edge documentation but have not found anything related to this.

Is there anyway to block this behavior so that the new version of Edge does not automatically pin itself to the task-bar? Also, is it possible to block the automatic desktop shortcut creation? I have tried using the registry key documented here, https://superuser.com/questions/1323943/prevent-edge-desktop-shortcut-on-new-profiles. That doesn't help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f9f4749-781c-04d7-48ab-bb406fb45b28
* Version Independent ID: 3976d362-f5b9-1c7b-7c15-0473b0c14fda
* Content: [Configure Microsoft Edge for Windows](https://docs.microsoft.com/en-us/deployedge/configure-microsoft-edge)
* Content Source: [edgeenterprise/configure-microsoft-edge.md](https://github.com/MicrosoftDocs/EdgeEnterprise/blob/public/edgeenterprise/configure-microsoft-edge.md)
* Product: **microsoft-edge**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **brianalt**

**Comment by wesleyan-ablackburn** [comment]
Just to clarify, I have set a default taskbar layout:
https://docs.microsoft.com/en-us/windows/configuration/configure-windows-10-taskbar

It seems new Edge ignores this.

**Comment by rlgura** [comment]
Why is this closed? I have the same question. Even though I'm using every master_preference option I could find, it's still pinning to the user's taskbar after launch
  "create_all_shortcuts": false,
  "do_not_create_any_shortcuts": true,
  "do_not_create_desktop_shortcut": true,
  "do_not_create_quick_launch_shortcut": true,
  "do_not_create_taskbar_shortcut": true,
