### ISSUE TITLE
HideFirstRunExperience does not appear as a valid Policy

### ISSUE THREAD

**Issue by mckoto** [MicrosoftDocs/EdgeEnterprise#65]
In Version 79.0.309.71 (Official build) (64-bit), **HideFirstRunExperience** does not appear to be a valid policy.

[edge://policy/](edge://policy/) (with "Show policies with no value" checked) does not display the **HideFirstRunExperience** policy.

In Group Policy Management Editor there does not appear to be a policy named "Hide the First-run experience and splash screen" under Administrative Templates/Microsoft Edge/ as described

I've re-downloaded the cab/adm/admx files from https://www.microsoft.com/en-us/edge/business/download and reviewed them and could not find a reference to **HideFirstRunExperience**

**Comment by jasminrueegger** [comment]
Yeah, the policy documentation also states that it is supported by version >= 80. 
It works with the DEV version. So just be patient

**Comment by mckoto** [comment]
I somehow missed that, thanks!
