### ISSUE TITLE
RestrictSigninToPattern policy not working

### ISSUE THREAD

**Issue by dinci5** [MicrosoftDocs/EdgeEnterprise#66]
I am trying to get this to work for days now but it doesn't work.

When this policy is enabled, we can't login with any account.
If we try to login with an account of the domain we specified, in the format **.*@ourdomain.com** an error message pops up.

**_Error:_**

> Your system administrator has not granted xxx@domain.com sign-in permissions. You can try another email address, or contact your system administrator for more access.

Screenshot: https://i.imgur.com/0IEtX9a.png

Account we try to use to login is an Office 365 "Work or school account".

**Comment by dinci5** [comment]
I did some more digging...
Turns out the pattern is Case Sensitive! (why??)

My Work account is Firstname.Lastname@MYDOMAIN.COM
If I change the pattern to: .*@MYDOMAIN.COM it works.
If I change the pattern to: .*@mydomain.com it does not work.

**Comment by dan-wesley** [comment]
@dinci5 By design, someone decided the pattern should be case sensitive. Sorry this has given you so much grief.
