### ISSUE TITLE
ManagedFavorites

### ISSUE THREAD

**Issue by saubermfg** [MicrosoftDocs/EdgeEnterprise#67]
I am not able to see "ManagedFavorites" as a setting in the GPO options, but I do see "Configure Favorites." It is unclear where the target file (presumably and HTML file) can reside, or what the format of the address should look like. Additionally, edge://policy shows a policy listed as "ManagedFavorites," but even with "Configure Favorites" enabled with some kind of value, this never gets pushed to the client. I am able to see other policy changes after a gpupdate /force and a policy refresh on Edge, just not this one. This will help us get off of Chrome for good, where we enjoy the managed bookmarks feature in the cloud right now.

Thanks!
John

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1cd3ad5-bb4a-54ff-84e7-18ca0b11368f
* Version Independent ID: 984abd8f-45eb-737b-ad74-07ec8261f9eb
* Content: [Microsoft Edge Browser Policy Documentation](https://docs.microsoft.com/en-us/DeployEdge/microsoft-edge-policies#feedback)
* Content Source: [edgeenterprise/microsoft-edge-policies.md](https://github.com/MicrosoftDocs/EdgeEnterprise/blob/public/edgeenterprise/microsoft-edge-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @Brianalt-Msft
* Microsoft Alias: **stmoody**

**Comment by jasminrueegger** [comment]
The GPO is called "Configure favorites". It takes a JSON-formatted String like this:
[{"toplevel_name":"Foldername"},{"url": "https://www.test.ch","name":"FavoriteName"}]
The GPO also has an Example, but I needed to loose the newlines to make it work.

**Comment by saubermfg** [comment]
@jasminrueegger wow, thanks a lot! I'll lose the newlines, but am curious how you formatted your address as to the location of this file. Also, what file type extension did you use (in case that matters).

**Comment by jasminrueegger** [comment]
There is no file involved. You enter the JSON-string directly into the field.

**Comment by saubermfg** [comment]
Awesome. Online JSON formatters are very helpful here :).

Thanks again @jasminrueegger
