### ISSUE TITLE
Force sync

### ISSUE THREAD

**Issue by Hadamuda** [MicrosoftDocs/EdgeEnterprise#68]
Is there anyway to force enable sync in an enterprise? Haven't been able to find any of the new gpo's which does that.

**Comment by dan-wesley** [comment]
@Hadamuda We're currently working on a GPO to handle this.

**Comment by Hadamuda** [comment]
> @Hadamuda We're currently working on a GPO to handle this.

Sounds great. Thanks for the answer.
