### ISSUE TITLE
Sync by Default

### ISSUE THREAD

**Issue by jhayesksb** [MicrosoftDocs/EdgeEnterprise#75]
Is there the ability to turn on syncing by default for user accounts in Shared PC situations? We are trialing Shared PC where the profile is removed from the machine either at logoff or when the during maintenance and we do not want the users to be prompted to enable syncing every time they login to a PC where their profile does not exist. Have I missed something?

**Comment by scottbo-msft** [comment]
This isn't supported right now, but it is a very popular request and we are looking into it. I suggest checking in periodically at the [Microsoft Edge roadmap](https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=Microsoft%20Edge) where we announce new features.

**Comment by dan-wesley** [comment]
@jhayesksb note Scott's feedback on this subject.
