### ISSUE TITLE
SAML authentication and Enterprise Mode list

### ISSUE THREAD

**Issue by rkrindges** [MicrosoftDocs/EdgeEnterprise#76]
Hello,
At our company, we have old sites that require Java applet, and for this, we need IE mode. In this site, the single sign-on is performed outside the application, in the Ping Federate product, using SAML protocol.
To make work altogether, we need to add both the old site and the Ping Federate domains in the Enterprise Mode list. 
The problem is, if we add the Ping Federate domain, all other sites that use this product for the single sign-on should be added as well.

As a workaround, we are thinking of creating a new domain alias for the Ping Federate product and adding this new alias to the list.

What I want to request is if it is possible to add a new feature, when a page opens in IE mode, all further pages that open in the same tab, remains in the IE mode. Or, if at the Enterprise Schema, we can add specific pages in the "site url", not only domains/subdomains.

**Comment by shisub** [comment]
@rkrindges - To make your scenario work, you would need to add the PingFederate domains as **neutral** to the site list. See [here](https://docs.microsoft.com/en-us/deployedge/edge-ie-mode#i-am-trying-to-go-to-a-site-in-ie-mode-and-it-appears-to-be-stuck-navigating-in-a-loop-or-tells-me-that-im-not-authenticated-whats-happening) for more information. 
Navigation to a neutral site stays where it started - either Edge or IE mode - and you will not need to add all the sites that use PingFederate for authentication into the site list.

**Comment by rkrindges** [comment]
Thank you very much!!! It worked just fine! :)
