### ISSUE TITLE
Edge startup method

### ISSUE THREAD

**Issue by HansKappert** [MicrosoftDocs/EdgeEnterprise#77]
Hi Team,
The document says: "&lt;local path&gt;\msedge.exe" --kiosk http://bing.com
but edge is started through protocol activation. So if you put this in a shortcut:
microsoft-edge:http://bing.com
Edge will start, but it will not accept a --kiosk parameter following the url.
msedge.exe is nowhere on my computer, but 
C:\Windows\SystemApps\Microsoft.MicrosoftEdge_8wekyb3d8bbwe\MicrosoftEdge.exe
is. Unfortunately, Edge will not start when called like this.
So my question is how to start Edge from the command line, providing the --kiosk parameter and an URL?
Kind regards,
Hans Kappert 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dec20919-0c5d-b6f8-eb24-c3b84ae01cba
* Version Independent ID: 516e7f67-7ff5-6dba-02b5-c411b361d1d9
* Content: [Microsoft Edge kiosk mode](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-kiosk-mode#feedback)
* Content Source: [edgeenterprise/microsoft-edge-kiosk-mode.md](https://github.com/MicrosoftDocs/EdgeEnterprise/blob/public/edgeenterprise/microsoft-edge-kiosk-mode.md)
* Product: **microsoft-edge**
* GitHub Login: @BrianAlt
* Microsoft Alias: **brianalt**

**Comment by pyoungberg** [comment]
New Edge is located at C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe
