### ISSUE TITLE
Release notes missing

### ISSUE THREAD

**Issue by pilgi3** [MicrosoftDocs/EdgeEnterprise#78]
At the landing page it is possible to download stable version 80.0.361.56. 
Where are the release notes for every version between 80.0.361.48 and 80.0.361.56?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fb3b598-06c4-80d8-6095-e790a184a12b
* Version Independent ID: ad7a2d15-1935-a76d-1823-e8dc347024b3
* Content: [Microsoft Edge release notes for Stable Channel in 2020](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-relnote-stable-channel#feedback)
* Content Source: [edgeenterprise/microsoft-edge-relnote-stable-channel.md](https://github.com/MicrosoftDocs/EdgeEnterprise/blob/public/edgeenterprise/microsoft-edge-relnote-stable-channel.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **kvice**

**Comment by AndyH16** [comment]
I could be wrong but there is a separate section 'Security updates' and this page contains notes related to some of the more recent updates. The notes on each just state "Incorporates the latest Security Updates of the Chromium project.", so it's possible this page might only list Microsoft-related changes to Edge.

**Comment by pilgi3** [comment]
So on this page i see only new entries when features were added i understand!
[https://docs.microsoft.com/en-us/deployedge/microsoft-edge-relnote-stable-channel](url)
Thank you!
