### ISSUE TITLE
Policies not taking effect - Edge Beta

### ISSUE THREAD

**Issue by UnidentifiedTag** [MicrosoftDocs/EdgeEnterprise#8]
I've added "msedge.adml" to "ROOT:\Windows\PolicyDefinitions\en-US" (ROOT is normally C:/) and "msedge.admx" to "ROOT:\Windows\PolicyDefinitions" following "Configure Microsoft Edge" guide along with the Policy File/zip. I've even added "msedge.adm" by right clicking with in Local Group Policy Editor, however the polices are just not taking effect, IE Mode wont enable and even setting the default home page wont apply. Edge Beta just behaves as if nothing has happened, edge://policy/ says : No policies set and edge://management/ says : Microsoft Edge is not managed by a company or organisation. nothing is working! 12 hours I've put in to this, Microsoft support or the Microsoft experts wasn't able to help me, the system is running Windows 8.1, KB4504418 and KB4507463 are installed and I've ran the "gpupdate /force" in an (admin) command prompt, i've also uninstalled edge and reinstalled it with (admin) rights.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aae869a8-2ae4-d28f-6c85-c1190609f87b
* Version Independent ID: e2bcb1d6-27f7-5e30-ae6b-7acb5ee94098
* Content: [Use Microsoft Edge with IE mode](https://docs.microsoft.com/en-us/deployedge/edge-ie-mode)
* Content Source: [edgeenterprise/edge-ie-mode.md](https://github.com/MicrosoftDocs/EdgeEnterprise-pr/blob/live/edgeenterprise/edge-ie-mode.md)
* Product: **microsoft-edge**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by RajGS** [comment]
@UnidentifiedTag - Home Page Location is a "protected policy", meaning, it will only work on machines that are managed, as indicated by the last line in the description of the policy (https://docs.microsoft.com/en-us/DeployEdge/microsoft-edge-policies#homepagelocation). Is the 8.1 system you tested this on a domain joined or a managed device? If not, could you please enroll it into a domain and try (both Home page and IE mode) policies again? Would love to hear back on how this goes.

**Comment by RajGS** [comment]
@UnidentifiedTag, to add, what SKU of Win 8.1 are you using?

**Comment by UnidentifiedTag** [comment]
@kelleyvice-msft - Version 77.0.235.15 (Official build) beta(32-bit) on Windows 8.1

**Comment by UnidentifiedTag** [comment]
![image](https://user-images.githubusercontent.com/54625394/63935634-d076fa80-ca55-11e9-9621-d17b400c8172.png)

Internet Explorer isn't showing the Enterprise Mode? Do I have to add a URL list ?

**Comment by UnidentifiedTag** [comment]
@RajGS - 
![image](https://user-images.githubusercontent.com/54625394/63936195-2a2bf480-ca57-11e9-9d86-f1ebf5050373.png)

**Comment by UnidentifiedTag** [comment]
it seems this might be a fault of my own :D adding group policy might not be working, your welcome to help if you know a work around or a fix, 

sorry for wasting everyone's time including my own

**Comment by UnidentifiedTag** [comment]
i would update the project explaining Windows 10 home, Windows 8.1 Home and Windows 7 Home / Starter / don't have the needed tools to get this functioning and it will need Windows 7 Pro or higher

**Comment by RajGS** [comment]
Thanks @UnidentifiedTag for the update! Glad to know that you're unblocked now :)

**Comment by UnidentifiedTag** [comment]
@RajGS - not sure what you mean by unblocked ? I still would like to get this working on my system

**Comment by RajGS** [comment]
@UnidentifiedTag, for your convenience, here are the relevant docs that discuss domain join and Group Policy management features availability for the various SKUs:

Windows 10: https://social.technet.microsoft.com/wiki/contents/articles/51209.microsoft-windows-10-features-editions.aspx
Windows 8.1: https://social.technet.microsoft.com/wiki/contents/articles/14374.windows-8-1-editions-skus-and-features.aspx
Windows 7: https://blogs.technet.microsoft.com/uspartner_ts2team/2010/02/26/windows-7-sku-lineup-understanding-your-options/

**Comment by UnidentifiedTag** [comment]
@RajGS - so what does this mean for me, im on windows 8.1?

**Comment by RajGS** [comment]
@UnidentifiedTag, sorry I didn't realize I was cross-posting when you asked your previous question. Can you please go to Control Panel > System and Security > System and check the entry under "Windows edition". It has to mention "Windows 8.1 Pro" or "Windows 8.1 Enterprise". If that's not the case, you'll have to move to one of these editions before you can try group policy and domain join features. 

Group policy feature support is required in the OS for you try out any group policy for Edge.
Domain join feature support is required in the OS+the device needs to be domain joined or managed (InTune, MDM/Workplace Enroll, etc), so that you can try the "protected policies" like HomePageLocation for example.

I found a couple of (non-Microsoft) articles I thought might be relevant for you:
Easily Change Windows 8.1 Edition Without Reinstalling: https://www.petri.com/change-windows-8-1-edition-without-reinstalling

You Can’t Use Them: 8 Features Only Available in Windows 8 Enterprise: https://www.howtogeek.com/195447/you-cant-use-them-8-features-only-available-in-windows-8-enterprise/

**Comment by UnidentifiedTag** [comment]
@RajGS - The Windows edition is Windows 8.1 (non pro) 

It would be great if you guys could work out away to get this to work on editions lower than windows 8.1 (non pro) home /starter and so on, 

on a side note i was on Windows 10 pro on this very device, but since build 1809 i had to downgrade as the kernal was updated in build 1809 so much that my device was no longer supported, when i contacted Microsoft support i was told to leave windows 10 pro and go back to what i was on before, but because the install before windows 10 pro was an oem i had lost it, i begged Microsoft support for downgrade rights and they said they couldn't do it cause it was oem, as a goodwill they put me on windows 8.1 (non pro) so this is why im trying to find away around it

**Comment by kelleyvice-msft** [comment]
@UnidentifiedTag, according to my sources, there is a bug that prevents IE mode from working properly on Windows 8.1, and the product team is working to resolve it now. I don't have any specific ETA on when the fix will be implemented, but I will update this issue when I have more information. However, from the last few entries in the thread, it sounds like this won't help you with your specific configuration.
I don't know if there are plans to eventually enable IE mode for Edge Enterprise on Home/Starter editions, but since IE mode functionality is intended for enterprise use, it doesn't seem likely.

**Comment by UnidentifiedTag** [comment]
@kelleyvice-msft - Now you guys decide to share with the rest of the group, indeed Windows 8.1 Pro does not support IE Mode as of 77.0.235.9 (Official build) beta (32-bit)

I can not tell you how much time I've invested in to this project, even getting Windows 8.1 Pro on here hasn't got it working as of yet, what i can share is my findings, 

any version of windows under pro will not work, even if you use the powershell line i talked about above because the polices do not take effect, 
after installing Windows 8.1 Pro ive found polices are taking effect and i am able to turn on enterprise mode with in Internet explorer, 
 on the edge Beta side of things edge://policy/ now shows a list of polices taking effect and edge://management/ now says "Microsoft Edge is managed by your organisation" so at least some things are working
![so annoying](https://user-images.githubusercontent.com/54625394/64266788-20116680-cf2d-11e9-82e0-22ae5a31941b.PNG)

Hopefully the edge team are putting this IE Mode as a top priority, for Windows 8.1 pro, some of us can't run the latest build of Windows 10 Pro because someone decided older hardware should be dropped from the newer builds

**Comment by kelleyvice-msft** [comment]
@UnidentifiedTag - I'm sorry this has been a frustrating and time-consuming experience for you. I certainly empathize, and I'm glad you have at least had some measure of success. I will pass along your request to prioritize IE mode for Windows 8.1 Pro, and we will update the Prerequisites section to clearly state the supported SKUs for each OS.
I really appreciate your willingness to share your issues and findings at this level of detail. Thanks very much for helping us improve our products and our documentation.
Regards,
Kelley

**Comment by UnidentifiedTag** [comment]
@kelleyvice-msft - it's been a month, any news on the fix for Windows 8.1 and Edge

**Comment by UnidentifiedTag** [comment]
I've tested the feature today and it looks to be working now finely
![Capture](https://user-images.githubusercontent.com/54625394/69068639-05736780-0a1d-11ea-837c-45295c937685.PNG)
