### ISSUE TITLE
ProgID in xml is incorrect

### ISSUE THREAD

**Issue by GijsFeerakkers** [MicrosoftDocs/EdgeEnterprise#81]
The ProgId="MSEdgeHTM" should be ProgId="MSEdgeHTML"

The L is missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d80a2f5-5b21-a16b-c401-5e1c40be6f00
* Version Independent ID: b63c5b42-443b-687c-a445-58fa4de6b84b
* Content: [Set Microsoft Edge as the default browser on Windows and macOS](https://docs.microsoft.com/en-us/deployedge/edge-default-browser#feedback)
* Content Source: [edgeenterprise/edge-default-browser.md](https://github.com/MicrosoftDocs/EdgeEnterprise/blob/public/edgeenterprise/edge-default-browser.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **brianalt**

**Comment by ziggyk80** [comment]
MSEdgeHTM is correct.  If you install Edge and go to Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Classes\.htm\OpenWithProgIds you will see it listed there as MSEdgeHTM.  I tested both ways and MSEdgeHTML did not work with Windows 10 LTSB 2016.
