### ISSUE TITLE
Bad Profile Path

### ISSUE THREAD

**Issue by mhendric** [MicrosoftDocs/EdgeEnterprise#87]
This article shows the profile path as:
C:\Users\&lt;Current-user&gt;\AppData\Local\MicrosoftEdge\User Data\Default

On my machine, the profile path is actually ( \ between Microsoft and Edge):
C:\Users\&lt;Current-user&gt;\AppData\Local\Microsoft\Edge\User Data\Default

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 493bec6b-d5b0-63b6-98e6-37506daafae8
* Version Independent ID: ea8be1d8-bf39-9e32-b0c1-8edb6e73e13e
* Content: [Create Microsoft Edge user data directory variables](https://docs.microsoft.com/en-us/deployedge/edge-learnmore-create-user-directory-vars#feedback)
* Content Source: [edgeenterprise/edge-learnmore-create-user-directory-vars.md](https://github.com/MicrosoftDocs/EdgeEnterprise/blob/public/edgeenterprise/edge-learnmore-create-user-directory-vars.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **brianalt**

**Comment by dan-wesley** [comment]
@mhendric Thanks for taking the time to point that out. We'll get it updated.

**Comment by RAJU2529** [comment]
@mhendric. where did you seen?
**C:\Users\<Current-user>\AppData\Local\MicrosoftEdge\User Data\Default**

I read the article completely, but I am unable to  get

**Comment by mhendric** [comment]
@RAJU2529 , it looks like @dan-wesley already fixed this:

https://github.com/MicrosoftDocs/EdgeEnterprise/commit/6e63da3d5b0ac448d4dda4970a4a609099f4cb23#diff-5b15f94f65b0849c32404b9e27859381

**Comment by RAJU2529** [comment]
@mhendric . Thanks I seen
