### ISSUE TITLE
OMA-URI Configuration

### ISSUE THREAD

**Issue by macmillernz** [MicrosoftDocs/EdgeEnterprise#9]
It would be great to see an easy guide to adding the OMA-URI configuration for Intune customers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f9f4749-781c-04d7-48ab-bb406fb45b28
* Version Independent ID: 3976d362-f5b9-1c7b-7c15-0473b0c14fda
* Content: [Configure Microsoft Edge](https://docs.microsoft.com/en-us/DeployEdge/configure-microsoft-edge#feedback)
* Content Source: [edgeenterprise/configure-microsoft-edge.md](https://github.com/MicrosoftDocs/EdgeEnterprise-pr/blob/live/edgeenterprise/configure-microsoft-edge.md)
* Product: **microsoft-edge**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **brianalt**

**Comment by Jcodedk** [comment]
Just use ADMX inside intune :)
