### ISSUE TITLE
Version Version 81.0.361.69: March 19 not correct

### ISSUE THREAD

**Issue by Alpha-89** [MicrosoftDocs/EdgeEnterprise#93]
This should be: Version 80.0.361.69: March 19

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fb3b598-06c4-80d8-6095-e790a184a12b
* Version Independent ID: ad7a2d15-1935-a76d-1823-e8dc347024b3
* Content: [Microsoft Edge release notes for Stable Channel](https://docs.microsoft.com/en-us/DeployEdge/microsoft-edge-relnote-stable-channel#feedback)
* Content Source: [edgeenterprise/microsoft-edge-relnote-stable-channel.md](https://github.com/MicrosoftDocs/EdgeEnterprise/blob/public/edgeenterprise/microsoft-edge-relnote-stable-channel.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **kvice**

**Comment by dan-wesley** [comment]
@Alpha-89 Thanks for catching this, will fix immediately.
